config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :authors
    resources :articles
    resources :article_categories
  end
  # mount Fae below your admin namespec
  mount Fae::Engine => '/admin'

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :comments
  resources :articles, param: :slug, only: [:index, :show]
  resources :users do
    member do
      get :edit_password
      get :edit_settings
    end
  end
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :init, only: [:index]

  namespace :api do
    namespace :v1 do
      resources :widget_inits, only: [:create]
      resources :users, only: [:show, :create, :update, :destroy]
      resources :user_sessions, only: [:new, :create, :destroy]
      resources :comments, only: [:index, :show, :create, :update, :destroy]
      resources :comment_filters, only: [:create]
      resources :votes, only: [:create, :update, :destroy]
      resources :followings, only: [:create]
      resources :unfollowings, only: [:create]
      resources :blockings, only: [:create]
      resources :unblockings, only: [:create]
      resources :arts, only: [:show]
      resources :gallery_blacklistings, only: [:create]
      resources :user_feedbacks, only: [:create]
      resources :user_video_clicks, only: [:create]
      resources :heatmaps, only: [:index]

      # this only lives here temporarily
      resources :admin_mails, only: [:create]
    end
  end


  # temp routes
  resources :admin_mails, only: [:new]

  ### named routes be here
  get 'register' => "users#new",           as: :register
  get 'login' => "user_sessions#new",      as: :login
  get 'logout' => "user_sessions#destroy", as: :logout

  # root
  root :to => 'articles#index'
end

app/models/article.rb
class Article < ApplicationRecord
  include Fae::BaseModelConcern

  self.per_page = 50

  belongs_to :article_category
  belongs_to :author

  has_many :article_topics
  has_many :ct_topics, through: :article_topics

  has_fae_image :thumbnail
  has_fae_image :banner
  has_fae_image :top_image
  has_fae_image :middle_image
  has_fae_image :footer_image

  before_validation :generate_slug!, on: :create

  validates :title, :publish_date, :introduction, :body, presence: true

  validates :slug, Fae.validation_helpers.slug

  def fae_display_field
    title
  end

  def art
    @art ||= Art.find_by(url: url)
  end

  def comments
    @comments ||= art.blank? ? [] : art.comments
  end

  def votes
    @votes ||= art.blank? ? [] : comments.map(&:votes).flatten
  end

  def url(request = {})
    if !request.blank? && !request.base_url.to_s.match('staging').nil?
      base_url = "classifilter-staging.herokuapp.com"
    elsif Rails.env.production?
      base_url = "api.cmmntz.com"
    elsif request.blank?
      base_url = "localhost:3000"
    else
      base_url = "#{request.base_url.gsub("http://", "")}"
    end
    "#{base_url}/#{self.class.to_s.pluralize.downcase}/#{slug}"

  end

  # dealing with topics
  def topics=(list)
    article_topics.destroy_all if article_topics
    list.split(",").each { |t| ct_topics << CtTopic.find_or_create_by(name: t.strip) }
  end

  def topics
    ct_topics.map(&:name).join(", ")
  end

  private

  def generate_slug!
    return unless publish_date && title
    self.slug = "#{publish_date.strftime("%Y-%m-%d")}-#{title.downcase.gsub(/[^0-9A-Za-z\s]/, '').gsub(" ", "-")}"
  end
end

app/controllers/admin/articles_controller.rb
module Admin
  class ArticlesController < Fae::BaseController

    private

    def build_assets
      @item.build_banner if @item.banner.blank?
      @item.build_thumbnail if @item.thumbnail.blank?
      @item.build_top_image if @item.top_image.blank?
      @item.build_middle_image if @item.middle_image.blank?
      @item.build_footer_image if @item.footer_image.blank?
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action *ALL_FILTERS - [:require_app_access, :create_guest_unless_logged_in]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    page = params[:page] || 1
    @articles = Article.order(publish_date: :desc).where("publish_date <= '#{Date.today}'").page(page).to_a
    @first_article = @articles.shift
    @second_article = @articles.shift
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    UserArticleView.create_for_user_and_article(current_user.id, @article.id)

    url = @article.url(request)
    @gallery = Gallery.find_by(name: "Customer Newspaper Site-Test")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find_by(slug: params[:slug])
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def article_image_link article
    link_to article_thumbnail_or_placeholder(article), article_path(article.slug)
  end
  def article_thumbnail_or_placeholder article, x_class = "img-fluid"
    if article.thumbnail.present? && article.thumbnail.asset.present?
      image_tag article.thumbnail.asset.url, class: "#{x_class}"
    else
      image_tag '/images/image-placeholder.jpg', class:  "#{x_class}"
    end
  end

  def article_banner article
    if article.banner.present? && article.banner.asset.present?
      image_tag article.banner.asset.url, class: "article-banner"
    end
  end

  def article_image article_image
    if article_image.present? && article_image.asset.present?
      image_tag article_image.asset.url, class: "img-fluid"
    end
  end

  def article_body_display_class article
    article.middle_image.present? && article.middle_image.asset.present? ? "col-sm-7" : "col-sm-12"
  end

  def widget_mode
    return if request.base_url.to_s.match('staging').nil?
    "mode: 'staging'".html_safe
  end
end

app/views/admin/articles/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  == render 'fae/shared/form_header', header: @klass_name

  main.content
    = fae_datepicker f, :publish_date
    = fae_input f, :title
    - unless f.object.new_record?
      = fae_input f, :slug, helper_text: 'Populated from publish date and name'
    = fae_association f, :author, {label: "Source"}
    = fae_association f, :article_category
    = fae_input f, :topics
    = fae_image_form f, :thumbnail
    = fae_input f, :introduction, markdown: true
    = fae_image_form f, :banner
    = fae_input f, :youtube_url
    = fae_input f, :body, markdown: true
    = fae_image_form f, :top_image
    = fae_input f, :body_2, markdown: true
    = fae_image_form f, :middle_image
    = fae_input f, :body_3, markdown: true
    = fae_image_form f, :footer_image

app/views/admin/articles/edit.html.slim
== render 'form'

app/views/admin/articles/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th Name
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.fae_display_field, edit_admin_article_path(item)
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/articles/new.html.slim
== render 'form'